name: Build EpiDoc Development Guidelines

on:
  push:
    branches: [ main ]
    paths:
      guidelines/xml/*.xml

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: teic/teidev-docker:latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0
      - name: "Checkout gh-pages branch"
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: "Build Guidelines"
        run: |
          xmllint --xinclude guidelines/xml/driver.xml > guidelines/xml/driver-ex.xml
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/epidoc-html.xsl -o:guidelines/output/index.html analytics="on" attsOnSameLine="2" ignoreXmlBase="true"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="ddbdp"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="dohnicht"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="edh-web"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="iospe"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="london"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="petrae"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="rib"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html leiden-style="seg"
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/output/index.html verse-lines="on"
          rsync -av --mkpath guidelines/output/ gh-pages/gl/dev/
      - name: "Push to gh-pages branch"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: gh-pages
          branch: gh-pages
          commit_message: "Published dev Guidelines."






