name: Build EpiDoc Development Guidelines

on:
  push:
    branches: [ main ]
    paths:
      schema/tei-epidoc.xml

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: teic/teidev-docker:latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0
      - name: "Checkout gh-pages branch"
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: "Build Schema"
        run: |
          guidelines/xslt/TEI-Stylesheets/bin/teitoodd schema/tei-epidoc.xml schema/tei-epidoc.compiled.xml
          guidelines/xslt/TEI-Stylesheets/bin/teitorelaxng schema/tei-epidoc.xml schema/tei-epidoc.rng
          saxon -s:guidelines/xml/driver-ex.xml -xsl:guidelines/xslt/createEpidocViews.xsl -o:guidelines/xml/views/ddbdp/examples.xml leiden-style="ddbdp"
          mkdir -p gh-pages/schema/dev
          cp schema/tei-epidoc.* gh-pages/schema/dev/
      - name: "Push to gh-pages branch"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: gh-pages
          branch: gh-pages
          commit_message: "Published development Schema."






